name: Build & Push Docker, Redeploy Render

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE: ghcr.io/seoptrike/portfolio_back
  TAG: prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker 이미지 빌드 & GHCR로 푸시
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/seoptrike/portfolio_back:prod
            ghcr.io/seoptrike/portfolio_back:${{ github.sha }}
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Render 재배포 트리거(Deploy Hook)
      - name: Trigger Render Deploy Hook
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
